# Generated by Django 2.2.4 on 2019-10-15 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(default='-', max_length=50, unique=True)),
                ('oe1', models.IntegerField(default=0)),
                ('oe2', models.IntegerField(default=0)),
                ('oe3', models.IntegerField(default=0)),
                ('pe1', models.IntegerField(default=0)),
                ('pe2', models.IntegerField(default=0)),
                ('pe3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lab Name')),
                ('labid', models.IntegerField(default=0, unique=True, verbose_name='Lab ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('IT', 'Information Technology')], max_length=4, verbose_name='Department')),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Year')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Semester')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('subjectid', models.IntegerField(default=0, unique=True, verbose_name='Subject ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('IT', 'Information Technology')], max_length=4, verbose_name='Department')),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Year')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Semester')),
                ('isopenelective', models.BooleanField(default=0, verbose_name='Open Elective')),
                ('isprofessionalelective', models.BooleanField(default=0, verbose_name='Professional Elective')),
                ('unit_1', models.TextField()),
                ('unit_2', models.TextField()),
                ('unit_3', models.TextField()),
                ('unit_4', models.TextField()),
                ('unit_5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('fullname', models.CharField(default='', max_length=50)),
                ('joiningyear', models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2022, verbose_name='Joining Year')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('IT', 'Information Technology')], max_length=4, verbose_name='Department')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectid', models.IntegerField(default=0, unique=True, verbose_name='Subject ID')),
                ('books', models.TextField(null=True)),
                ('web', models.TextField(null=True, verbose_name='Web Sources')),
                ('subject', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseinformation.Subject')),
            ],
        ),
    ]
